{-|
Module      : Monoid
Description : Finitely presented commutative monoids of stacking labels and their
              Grothendieck group completion (the algorithmic content of Section 4).
Copyright   : (c) Matthew Long, 2026
License     : MIT
Maintainer  : matthew@yonedaai.com
Stability   : experimental

Companion code for Part IV, "From Lattice Models to Effective Field Theories:
Stabilization and the Invertible Condensed Phase Spectrum".

Section 4 of the paper: the stacking operation @boxtimes@ makes the set of phases
a commutative monoid, and group completion (the Grothendieck construction) forces
inverses.  This module implements

  * a computable finitely presented commutative monoid, represented by a carrier
    of exponent vectors together with an idempotent normal form and a finite set
    of candidate /stabilization elements/;
  * the algorithmic group completion @K(M)@ of Definition 4.1 and Theorem 4.2,
    with equality decided by the stable-equality test of Proposition 4.4
    (@a + e == b + e@ for some witness @e@); and
  * the induced homomorphism of the universal property, Theorem 4.2(iii).

Two concrete monoids are provided: the free commutative monoid (cancellative,
completing to a free abelian group) and the non-cancellative toy monoid
@<a,t | t + a = t>@ of Example 4.5: the generator @a@ collapses
(@gamma a = gamma 0@), but @t@ survives, so the completion is @K(M) ~= Z@,
generated by @[t]@, /not/ @0@ (see "Proofs" for a proof of this from the
universal property).
-}
module Monoid
  ( -- * Elements
    Elt
  , gen, zero, plus, scale, degree, generatorsOf
    -- * Computable commutative monoids
  , CMonoid, cName
  , eqM, normalise
  , respectsAlphabet
    -- * Concrete monoids
  , freeCMonoid
  , toyMonoid
    -- * Group completion
  , GElt(..)
  , gamma, negG, plusG, zeroG
  , eqG, isTrivialG
    -- * Universal property
  , Hom
  , weightHom
  , induced
  , mkHom
    -- * Demonstrations
  , describeCompletion
  ) where

import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map
import Data.List (intercalate, sort)
import Numeric.Natural (Natural)

-- ---------------------------------------------------------------------------
-- Elements of a finitely presented commutative monoid
-- ---------------------------------------------------------------------------

-- | An element is an exponent vector over named generators, all exponents
-- nonnegative.  An absent key denotes exponent @0@.
newtype Elt = Elt (Map String Integer) deriving (Eq, Ord)

-- Additive notation, matching the paper: @0@, @a@, @2a@, @2a + b@, @a + t@.
instance Show Elt where
  show (Elt m)
    | Map.null nz = "0"
    | otherwise   = intercalate " + " [ term g e | (g, e) <- Map.toList nz ]
    where
      nz       = Map.filter (/= 0) m
      term g 1 = g
      term g e = show e ++ g

-- | The generator @g@ with exponent @1@.
gen :: String -> Elt
gen g = Elt (Map.singleton g 1)

-- | The monoid unit: all exponents zero.
zero :: Elt
zero = Elt Map.empty

-- | Monoid operation: pointwise sum of exponent vectors.
plus :: Elt -> Elt -> Elt
plus (Elt a) (Elt b) = Elt (Map.filter (/= 0) (Map.unionWith (+) a b))

-- | Multiply every exponent by a natural number (repeated stacking).  The
-- argument type is 'Natural', not 'Integer', so a negative multiplier is
-- rejected at runtime by 'Natural's underflow check (an arithmetic
-- exception when the literal is forced) rather than silently producing an
-- 'Elt' with negative exponents, which would violate the invariant
-- documented above.  (This is not a *compile-time* type error -- numeric
-- literals are polymorphic, so @scale (-1) x@ still typechecks -- but
-- negative exponents remain unrepresentable in any value that is actually
-- evaluated.)
scale :: Natural -> Elt -> Elt
scale n (Elt a) = Elt (Map.filter (/= 0) (Map.map (* toInteger n) a))

-- | Total degree (sum of exponents).
degree :: Elt -> Integer
degree (Elt a) = sum (Map.elems a)

-- | The generators actually occurring (with nonzero exponent).
generatorsOf :: Elt -> [String]
generatorsOf (Elt a) = sort [ g | (g, e) <- Map.toList a, e /= 0 ]

-- ---------------------------------------------------------------------------
-- Computable commutative monoids
-- ---------------------------------------------------------------------------

-- | A computable commutative monoid: an idempotent normal form making equality
-- decidable, together with a finite list of candidate /stabilization elements/
-- @e@ used to decide the stable equality @a + e == b + e@ that governs the
-- group completion (Proposition 4.4).  The unit @0@ is always an implicit
-- witness, so @cWitnesses@ need only list the extra ones a presentation needs.
-- @cGenerators@ records the presentation's declared alphabet (checkable via
-- 'respectsAlphabet') and @cRespects@ decides whether a weight assignment
-- respects the presentation's relations (used by 'mkHom').  The constructor
-- is /not/ exported: both @cWitnesses@ (soundness of 'eqG', a bounded search,
-- not the unbounded search the Grothendieck relation literally quantifies
-- over) and @cRespects@ are proof obligations on whoever builds a value of
-- this type, so only the two certified values below, 'freeCMonoid' and
-- 'toyMonoid', are ever constructed.
data CMonoid = CMonoid
  { cName       :: String
  , cGenerators :: [String]            -- ^ the declared generator alphabet
  , cnf         :: Elt -> Elt          -- ^ idempotent normal form; equality is (==) on @cnf@
  , cWitnesses  :: [Elt]               -- ^ extra candidate stabilization elements
  , cRespects   :: Map String Integer -> Bool
      -- ^ does a weight assignment respect this monoid's relations? (see 'mkHom')
  }

-- | Normal form under the monoid's presentation.
normalise :: CMonoid -> Elt -> Elt
normalise = cnf

-- | Decidable equality in the monoid: equal normal forms.
eqM :: CMonoid -> Elt -> Elt -> Bool
eqM m x y = cnf m x == cnf m y

-- | The free commutative monoid on a set of generators.  It is cancellative, so
-- the normal form is the identity and no stabilization element beyond @0@ is
-- ever needed; its group completion is the corresponding free abelian group.
freeCMonoid :: [String] -> CMonoid
freeCMonoid gs = CMonoid
  { cName       = "free commutative monoid"
  , cGenerators = gs
  , cnf         = id
  , cWitnesses  = []
  , cRespects   = const True   -- no relations: every weight assignment is valid
  }

-- | The non-cancellative toy monoid @<a, t | t + a = t>@ of Example 4.5.  The
-- generator @t@ absorbs @a@: whenever @t@ is present (exponent @>= 1@) every @a@
-- disappears.  Normal forms are @a^n@ (@n >= 0@) and @t^m@ (@m >= 1@, with the
-- @a@'s dropped).  The stabilization element @t@ witnesses @a + t = t = 0 + t@,
-- so @gamma a = gamma 0@ -- but @t@ itself is never absorbed (no relation
-- reduces any power of @t@), so the whole group completion is @K(M) ~= Z@,
-- generated by @[t]@, /not/ @0@.
toyMonoid :: CMonoid
toyMonoid = CMonoid
  { cName       = "toy monoid <a,t | t+a=t>"
  , cGenerators = ["a", "t"]
  , cnf         = \(Elt e) ->
      let t = Map.findWithDefault 0 "t" e
      in if t >= 1
           then Elt (Map.filter (/= 0) (Map.insert "a" 0 e))  -- t present: drop the a's
           else Elt (Map.filter (/= 0) e)
  , cWitnesses  = [gen "t"]
  , cRespects   = \w -> Map.findWithDefault 0 "a" w == 0
      -- ^ the only relation is @t+a=t@, i.e. @f(t)+f(a)=f(t)@, which by
      -- cancellation in @Z@ holds iff @f(a)=0@; see "Proofs" for the
      -- executable check of this equivalence.
  }

-- | Does every generator occurring in @x@ lie in @m@'s declared alphabet
-- ('cGenerators')?  The presentation's operations ('gen', 'plus', 'scale')
-- do not themselves enforce this -- a monoid only /declares/ its intended
-- generators -- so this lets a caller check an element was built honestly
-- against a specific monoid's alphabet.
respectsAlphabet :: CMonoid -> Elt -> Bool
respectsAlphabet m x = all (`elem` cGenerators m) (generatorsOf x)

-- ---------------------------------------------------------------------------
-- Group completion  K(M) = (M x M)/~
-- ---------------------------------------------------------------------------

-- | An element of the group completion, written as a formal difference
-- @GElt a b@ representing @a - b@ (Definition 4.1).
data GElt = GElt Elt Elt deriving (Eq, Ord)

instance Show GElt where
  show (GElt a b) = "(" ++ show a ++ ") - (" ++ show b ++ ")"

-- | The canonical map @gamma : M -> K(M)@, @m |-> [m - 0]@.
gamma :: Elt -> GElt
gamma a = GElt a zero

-- | Negation in @K(M)@: @-(a - b) = b - a@.
negG :: GElt -> GElt
negG (GElt a b) = GElt b a

-- | Addition in @K(M)@.
plusG :: GElt -> GElt -> GElt
plusG (GElt a b) (GElt c d) = GElt (plus a c) (plus b d)

-- | The identity of @K(M)@.
zeroG :: GElt
zeroG = GElt zero zero

-- | Equality in @K(M)@ (Definition 4.1, decided via Proposition 4.4):
-- @(a - b) = (c - d)@ iff there is a stabilization element @e@ with
-- @a + d + e == c + b + e@ in @M@.  The search ranges over @0@ and the
-- monoid's declared 'cWitnesses' -- a /bounded/ search, not the search over
-- all of @M@ that the Grothendieck relation literally quantifies over.  This
-- is sound exactly when 'cWitnesses' already contains a complete witness set
-- for @m@'s presentation: true by construction for 'freeCMonoid' (cancellative,
-- so @e=0@ always suffices) and for 'toyMonoid' (whose only relation @t+a=t@
-- makes @t@ the sole witness Example 4.5 ever needs). Completeness of
-- @cWitnesses@ is therefore a proof obligation on whoever builds a 'CMonoid',
-- which is exactly why the constructor is not exported: only these two
-- certified values are.
eqG :: CMonoid -> GElt -> GElt -> Bool
eqG m (GElt a b) (GElt c d) =
  any (\e -> eqM m (a `plus` d `plus` e) (c `plus` b `plus` e))
      (zero : cWitnesses m)

-- | Is a class trivial in the group completion?
isTrivialG :: CMonoid -> GElt -> Bool
isTrivialG m g = eqG m g zeroG

-- ---------------------------------------------------------------------------
-- Universal property (Theorem 4.2(iii))
-- ---------------------------------------------------------------------------

-- | A monoid homomorphism @M -> (Z, +)@.  It must respect the relations of the
-- presentation; 'weightHom' builds valid ones and the properties check the
-- well-definedness that Theorem 4.2(iii) needs.
type Hom = Elt -> Integer

-- | The homomorphism @M -> (Z,+)@ assigning integer weights to generators and
-- extending additively.  For it to descend to @M@ (respect the relations) the
-- weights must satisfy them; e.g. for the toy monoid @t + a = t@ forces the
-- weight of @a@ to be @0@.
weightHom :: Map String Integer -> Hom
weightHom w (Elt e) =
  sum [ Map.findWithDefault 0 g w * ex | (g, ex) <- Map.toList e ]

-- | The unique group homomorphism @K(M) -> A@ induced by @f : M -> A@ via the
-- universal property (Theorem 4.2(iii)): @fbar (a - b) = f a - f b@.
induced :: Hom -> GElt -> Integer
induced f (GElt a b) = f a - f b

-- | Build a 'Hom' /certified/ to respect @m@'s relations, using @m@'s own
-- 'cRespects' predicate; 'Nothing' if the weights do not respect them. A
-- 'Hom' built this way is guaranteed well defined on 'eqG'-classes (the
-- well-definedness step of Theorem IV-A(iii) \/ Proposition 4.4), unlike one
-- built directly from 'weightHom', which performs no such check and can be
-- fed to 'induced' regardless.
mkHom :: CMonoid -> Map String Integer -> Maybe Hom
mkHom m w
  | cRespects m w = Just (weightHom w)
  | otherwise     = Nothing

-- ---------------------------------------------------------------------------
-- Demonstration helper
-- ---------------------------------------------------------------------------

-- | A human-readable line describing @gamma x@ and whether it is trivial in the
-- group completion of the given monoid.
describeCompletion :: CMonoid -> Elt -> String
describeCompletion m x =
  "  " ++ pad 10 (show x)
        ++ " |-> gamma = " ++ pad 16 (show (gamma x))
        ++ "  trivial in K(M)? " ++ show (isTrivialG m (gamma x))
  where
    pad n s = s ++ replicate (max 0 (n - length s)) ' '
