{-|
Module      : Main (proofs test-suite)
Description : Equational proofs and deterministic checks for Part IV: the
              universal property of group completion, the toy monoid's
              collapse to Z, and the algebraic mechanism behind Bott
              periodicity.
Copyright   : (c) Matthew Long, 2026
License     : MIT
Maintainer  : matthew@yonedaai.com
Stability   : experimental

Companion code for Part IV, "From Lattice Models to Effective Field Theories:
Stabilization and the Invertible Condensed Phase Spectrum". Where
"Properties" samples the paper's claims randomly (QuickCheck), this module
proves them: each section gives an explicit equational derivation in a
Haddock comment -- mirroring the paper's own proof -- and an executable,
deterministic (non-random) check of the concrete instances and finite ranges
the derivation covers.

  * __Section 1__ (Theorem IV-A \/ Theorem 4.2, @thm:groth@): @gamma@ is a
    monoid homomorphism and every group-completion element decomposes as
    @gamma a - gamma b@, both /definitionally/; the toy monoid's relation
    @t+a=t@ forces any homomorphism out of it to send @a@ to @0@; and the
    induced map's well-definedness and factorization (Theorem 4.2(iii),
    Proposition 4.4) are exhibited on concrete witnesses, together with a
    demonstration that the well-definedness hypothesis is not vacuous: drop
    it and @induced@ becomes genuinely ill-defined.
  * __Section 2__ (Example 4.5, @ex:noncanc@): @K(\<a,t|t+a=t\>)@ is isomorphic
    to @Z@, generated by @[t]@, with @[a]=0@ -- established (on the
    generator-restricted carrier and a finite witnessed range) from the universal property itself,
    via the induced homomorphism to @Z@ that reads off the @t@-exponent,
    rather than from case analysis on normal forms.
  * __Section 3__ (Proposition 5.8, @prop:bott@): Bott periodicity and
    antidiagonal invariance are traced to their algebraic mechanisms --
    periodicity to the periodicity of integer @mod@, antidiagonal invariance
    to the plain arithmetic identity @(s+1)-(d+1)=s-d@ -- and Table 1's five
    named landmark entries are re-derived with the index arithmetic shown
    explicitly.
-}
module Main (main) where

import qualified Data.Map.Strict as Map
import Numeric.Natural (Natural)
import System.Exit (exitFailure, exitSuccess)

import Monoid
import TenfoldWay

-- ---------------------------------------------------------------------------
-- Shared generators
-- ---------------------------------------------------------------------------

a, t, b :: Elt
a = gen "a"
t = gen "t"
b = gen "b"

-- ---------------------------------------------------------------------------
-- Section 1 (Theorem IV-A / Theorem 4.2, thm:groth): the universal property
-- ---------------------------------------------------------------------------

-- | 'gamma' is /definitionally/ a monoid homomorphism (Theorem IV-A(ii)): no
-- witness search is needed, because @gamma m = GElt m zero@ and @plus x zero
-- = x@ on the nose (the carrier's smart constructors keep every 'Elt' already
-- filtered of zero exponents, so unioning with the empty map is a no-op).
-- Equational chain:
--
-- > plusG (gamma m) (gamma n)
-- >   = plusG (GElt m zero) (GElt n zero)      -- unfold gamma
-- >   = GElt (plus m n) (plus zero zero)       -- unfold plusG
-- >   = GElt (plus m n) zero                   -- plus zero zero = zero
-- >   = gamma (plus m n)                       -- fold gamma
--
-- every step an equality of 'Elt' \/ 'GElt' values on the nose, not merely up
-- to 'eqG'.
gammaHomomorphism :: Elt -> Elt -> Bool
gammaHomomorphism m n = plusG (gamma m) (gamma n) == gamma (plus m n)

-- | The structural identity underlying uniqueness in Theorem IV-A(iii): every
-- pair @GElt a b@ /is/, on the nose, @gamma a@ plus the negation of @gamma b@:
--
-- > GElt x y
-- >   = GElt (plus x zero) (plus zero y)                    -- unit law
-- >   = plusG (GElt x zero) (GElt zero y)                   -- unfold plusG
-- >   = plusG (gamma x) (negG (GElt y zero))                -- unfold negG
-- >   = plusG (gamma x) (negG (gamma y))                    -- fold gamma
--
-- Consequently any group homomorphism @g@ with @g . gamma = f@ must satisfy
-- @g (GElt x y) = g (gamma x) - g (gamma y) = f x - f y@ (using that @g@ is
-- additive and @g . negG = negate . g@), which is exactly @induced f (GElt x
-- y)@: the formula for @induced@ is therefore /forced/, not merely /a/
-- choice -- this is the uniqueness half of Theorem IV-A(iii).
differenceDecomposition :: Elt -> Elt -> Bool
differenceDecomposition x y = GElt x y == plusG (gamma x) (negG (gamma y))

-- | The relation forced on any homomorphism out of the toy monoid
-- @\<a,t|t+a=t\>@ (quoted directly from "Monoid"'s Haddock for 'weightHom'):
-- @f(t+a)=f(t)@ forces @f(a)=0@ by cancellation in @Z@. Checked exhaustively
-- over a range of candidate weights: it always holds when @f(a)=0@, and
-- always fails otherwise.
respectsToyRelation :: Integer -> Integer -> Bool
respectsToyRelation wa wt =
  let f = weightHom (Map.fromList [("a", wa), ("t", wt)])
  in f (plus t a) == f t

-- | A fixed nontrivial homomorphism @M -> Z@ respecting the toy monoid's
-- relation (@a@ forced to weight @0@), used as the running witness for the
-- rest of this section.
toyHomWitness :: Hom
toyHomWitness = weightHom (Map.fromList [("a", 0), ("t", 7), ("b", 5)])

-- | Existence and factorization (Theorem IV-A(iii)): @induced f@ recovers
-- @f@ along @gamma@, i.e. @induced f . gamma = f@. Note this holds by
-- construction for /any/ @f@ built from 'weightHom' -- @gamma x = GElt x
-- zero@ and @f zero = 0@ always, so @induced f (gamma x) = f x - f zero = f
-- x@ regardless of whether @f@ respects the presentation. It is therefore a
-- wiring \/ regression check on 'induced' and 'gamma', not yet a test of
-- well-definedness /across representatives/ -- that is
-- 'wellDefinednessInstance' below, where the choice of representative
-- actually matters.
factorizationWitness :: Elt -> Bool
factorizationWitness x = induced toyHomWitness (gamma x) == toyHomWitness x

-- | Well-definedness (Theorem IV-A(iii) \/ Proposition 4.4): two /different/
-- representatives of the same class in @K(toy monoid)@ -- @GElt a zero@
-- (i.e. @[a]@) and @GElt zero zero@ (i.e. @[0]@), identified via the
-- stabilization witness @e=t@ from Example 4.5 -- give the /same/ value
-- under @induced toyHomWitness@, even though the representatives themselves
-- are structurally distinct (@a \/= zero@ as raw carrier elements).
wellDefinednessInstance :: Bool
wellDefinednessInstance =
  eqG toyMonoid (GElt a zero) (GElt zero zero)
    && induced toyHomWitness (GElt a zero) == induced toyHomWitness (GElt zero zero)

-- | Necessity of the well-definedness hypothesis, enforced by construction:
-- 'mkHom' /rejects/ a weight assignment that does not respect the toy
-- monoid's relation (weight @1@ on @a@ instead of the forced @0@), returning
-- 'Nothing' instead of silently handing back a 'Hom' that 'induced' would
-- later disagree on across representatives (as 'wellDefinednessInstance's
-- pair would, with such an @f@). This is why Theorem IV-A(iii) requires @f@
-- to be a genuine monoid homomorphism on @M@ (not an arbitrary weighting of
-- generators): the hypothesis is doing real work, not decoration, and
-- 'mkHom' is the certified constructor that checks it rather than trusting
-- the caller.
rejectsBadWeighting :: Bool
rejectsBadWeighting =
  case mkHom toyMonoid (Map.fromList [("a", 1), ("t", 7)]) of
    Nothing -> True
    Just _  -> False

-- | ...and dually, 'mkHom' /accepts/ a weighting that does respect the
-- relation -- the running witness 'toyHomWitness' itself.
acceptsGoodWeighting :: Bool
acceptsGoodWeighting =
  case mkHom toyMonoid (Map.fromList [("a", 0), ("t", 7), ("b", 5)]) of
    Just _  -> True
    Nothing -> False

-- | A small spread of concrete elements (over the alphabet @{a,b,t}@) used to
-- spot-check the definitional lemmas above.
sampleElts :: [Elt]
sampleElts =
  [ zero, a, t, b
  , plus a t, plus (scale 2 a) b, plus (scale 3 t) (scale 2 a)
  , scale 5 a, scale 4 t, plus a (plus t b)
  ]

check_gammaHom :: Bool
check_gammaHom = and [ gammaHomomorphism m n | m <- sampleElts, n <- sampleElts ]

check_differenceDecomp :: Bool
check_differenceDecomp = and [ differenceDecomposition x y | x <- sampleElts, y <- sampleElts ]

check_respectsToyRelation :: Bool
check_respectsToyRelation =
  and [ respectsToyRelation 0 wt | wt <- [-5 .. 5] ]
    && and [ not (respectsToyRelation wa wt) | wa <- [-5, -3, -1, 1, 2, 4], wt <- [-3 .. 3] ]

check_factorization :: Bool
check_factorization = all factorizationWitness sampleElts

-- ---------------------------------------------------------------------------
-- Section 2 (Example 4.5, ex:noncanc): K(toy monoid) = Z, generated by [t]
-- ---------------------------------------------------------------------------

-- | The homomorphism @K(toy monoid) -> Z@ reading off the exponent of @t@: it
-- is exactly 'induced' (Theorem IV-A(iii)) applied to the weight assignment
-- forced by the relation (@a |-> 0@, @t |-> 1@). It is well defined on
-- 'eqG'-classes precisely because that weighting respects the relation (see
-- Section 1): @toyMonoid@'s normal form only ever /drops/ @a@'s, and a weight
-- of @0@ on @a@ makes that drop invisible to the weight sum.
toZ :: GElt -> Integer
toZ = induced (weightHom (Map.fromList [("a", 0), ("t", 1)]))

-- | @toZ@'s underlying weighting is exactly the one 'mkHom' certifies as
-- respecting the toy monoid's relation (@a |-> 0@) -- confirmed here by
-- construction, tying Section 1's certified-homomorphism mechanism directly
-- to the @K(M) ~= Z@ isomorphism of this section.
toZWeightingIsCertified :: Bool
toZWeightingIsCertified =
  case mkHom toyMonoid (Map.fromList [("a", 0), ("t", 1)]) of
    Just _  -> True
    Nothing -> False

-- | The candidate inverse @Z -> K(toy monoid)@, @n |-> n . [t]@ (Example 4.5).
-- @scale@ itself only accepts a 'Natural' multiplier, so the branches convert
-- the already-nonnegative @n@ \/ @negate n@ before calling it.
fromZ :: Integer -> GElt
fromZ n
  | n >= 0    = gamma (scale (fromIntegral n) t)
  | otherwise = negG (gamma (scale (fromIntegral (negate n)) t))

-- | @t^q@ is literally (no 'normalise' \/ 'eqG' needed) the @q@-fold sum of
-- @t@ with itself: 'scale' multiplies a single generator's exponent, which is
-- the same as repeated addition. Checked by unrolling the fold for @q=0..8@.
tPowerIsRepeatedSum :: Natural -> Bool
tPowerIsRepeatedSum q =
  scale q t == foldr plus zero (replicate (fromIntegral q) t)

-- | Theorem IV-A(ii) specialized: since @gamma@ is additive (@gammaHomomorphism@)
-- and @t^q@ is the @q@-fold sum of @t@ ('tPowerIsRepeatedSum'), @gamma(t^q)@
-- is the @q@-fold 'plusG'-sum of @gamma t@ -- i.e. @[t^q] = q . [t]@ in
-- @K(M)@, definitionally, with no appeal to normal forms.
gammaOfTPowerIsQCopies :: Natural -> Bool
gammaOfTPowerIsQCopies q =
  gamma (scale q t) == foldr plusG zeroG (replicate (fromIntegral q) (gamma t))

-- | Example 4.5, first half: @a@ collapses to @0@ in @K(M)@ for /every/
-- multiple of @a@ (not just @a@ itself), uniformly witnessed by @e=t@: for
-- @p>=1@, @normalise(p.a + t) = t = normalise(0 + t)@ since the toy monoid's
-- normal form drops all @a@'s whenever @t@ is present.
aMultiplesCollapse :: Natural -> Bool
aMultiplesCollapse p = isTrivialG toyMonoid (gamma (scale p a))

-- | @toZ@ is a one-sided inverse of @fromZ@ on all of @Z@: @toZ (fromZ n) =
-- n@. Since @fromZ n = n . gamma t@ and @toZ@ is (the restriction of) the
-- weight-@1@-on-@t@ homomorphism, this is immediate from additivity; checked
-- directly for @n@ in @[-8..8]@.
toZFromZRoundTrip :: Integer -> Bool
toZFromZRoundTrip n = toZ (fromZ n) == n

-- | Injectivity of @fromZ@ (hence of @n |-> [n.t]@): if two multiples of @t@
-- agreed in @K(M)@, applying the homomorphism @toZ@ -- well defined on
-- 'eqG'-classes because its underlying weight respects the relation (Section
-- 1) -- would force @i=j@ via 'toZFromZRoundTrip'. This re-derives
-- @Properties.prop_toyTPowersDistinct@ from the universal property, instead
-- of from case analysis on normal forms.
fromZInjective :: Integer -> Integer -> Bool
fromZInjective i j
  | i == j    = True
  | otherwise = not (eqG toyMonoid (fromZ i) (fromZ j))

-- | Representative pairs ranging over the four combinations of @a@-type \/
-- @t@-type generators discussed in Example 4.5, used to test surjectivity of
-- @fromZ@ onto the @a,t@-generated part of @K(M)@.
atCarrier :: [GElt]
atCarrier =
  [ GElt x y
  | x <- [zero, a, scale 2 a, t, scale 3 t, plus a t]
  , y <- [zero, a, scale 4 a, t, scale 2 t, plus (scale 2 a) t]
  ]

-- | Surjectivity: every class built from @a@ and @t@ is @fromZ@ of some
-- integer, namely @toZ@ of itself -- the witness in both directions is
-- always @e=t@, since adding @t@ collapses whatever @a@'s are present on
-- either side down to the same power of @t@.
roundTripOntoCarrier :: GElt -> Bool
roundTripOntoCarrier g = eqG toyMonoid (fromZ (toZ g)) g

-- ---------------------------------------------------------------------------
-- Section 3 (Proposition 5.8, prop:bott): Bott periodicity and landmarks
-- ---------------------------------------------------------------------------

-- | The single algebraic fact behind all Bott periodicity (Proposition 5.8):
-- integer @mod@ is periodic in its dividend with period equal to the
-- modulus. Periodicity of 'entryReal' \/ 'entryComplex' in @d@ is this
-- identity applied to @x = s-d@, @p=8@ or @p=2@.
modPeriodic :: Integer -> Integer -> Bool
modPeriodic x p = (x + p) `mod` p == x `mod` p

-- | The mod-periodicity mechanism, transported through 'entryReal' \/
-- 'entryComplex': checked exhaustively (not randomly) over a grid of
-- symmetry indices and dimensions, for both Bott periods.
check_modPeriodic :: Bool
check_modPeriodic =
  and [ modPeriodic (toInteger (s - d)) 8
          && entryReal s d == entryReal s (d + 8)
          && entryReal s d == entryReal (s + 8) d
      | s <- [-10 .. 10], d <- [-10 .. 10] ]
    && and [ modPeriodic (toInteger (s - d)) 2
               && entryComplex s d == entryComplex s (d + 2)
           | s <- [-10 .. 10], d <- [-10 .. 10] ]

-- | Antidiagonal invariance needs no modular reasoning at all, only the
-- identity @(s+1)-(d+1)=s-d@: /even more/ elementary than periodicity.
antidiagIsPlainArithmetic :: Int -> Int -> Bool
antidiagIsPlainArithmetic s d = (s + 1) - (d + 1) == s - d

-- | The antidiagonal-invariance mechanism, transported through 'entryReal' \/
-- 'entryComplex', checked exhaustively over a grid of symmetry indices and
-- dimensions.
check_antidiagonal :: Bool
check_antidiagonal =
  and [ antidiagIsPlainArithmetic s d
          && entryReal s d == entryReal (s + 1) (d + 1)
          && entryComplex s d == entryComplex (s + 1) (d + 1)
      | s <- [-10 .. 10], d <- [-10 .. 10] ]

-- | Table 1's five named landmark entries (quoted verbatim from the table
-- caption), each with the explicit index arithmetic @(s-d) mod p@ recorded
-- alongside the physical name.
landmarks :: [(String, Ab, Int, Int, Int)]
landmarks =
  [ ("Kitaev chain: class D, d=1",         Z2, 2, 1, 8)
  , ("p+ip superconductor: class D, d=2",  Z,  2, 2, 8)
  , ("quantum spin Hall: class AII, d=2",  Z2, 4, 2, 8)
  , ("3D topological insulator: AII, d=3", Z2, 4, 3, 8)
  , ("integer quantum Hall: class A, d=2", Z,  0, 2, 2)
  , ("SSH chain: class AIII, d=1",         Z,  1, 1, 2)
  ]

-- | Re-derive one landmark's invariant from the raw @(s-d) mod p@ index into
-- the appropriate Bott sequence, rather than via 'entryReal' \/
-- 'entryComplex', as an independent arithmetic cross-check.
landmarkHolds :: (String, Ab, Int, Int, Int) -> Bool
landmarkHolds (_, expected, s, d, p) =
  let idx    = (s - d) `mod` p
      actual = if p == 8 then realSeq !! idx else complexSeq !! idx
  in actual == expected

check_landmarks :: Bool
check_landmarks = all landmarkHolds landmarks

-- | The same six landmarks via the class-indexed entry point 'invariant',
-- confirming 'entryReal' \/ 'entryComplex' \/ 'field' \/ 'symIndex' agree with
-- the raw index arithmetic of 'landmarks'.
landmarksByClass :: [(AZClass, Int, Ab)]
landmarksByClass =
  [ (D, 1, Z2), (D, 2, Z), (AII, 2, Z2), (AII, 3, Z2), (A, 2, Z), (AIII, 1, Z) ]

check_landmarksByClass :: Bool
check_landmarksByClass = all (\(cls, d, expected) -> invariant cls d == expected) landmarksByClass

-- ---------------------------------------------------------------------------
-- Runner
-- ---------------------------------------------------------------------------

-- | Print one named deterministic check and return whether it passed.
check :: String -> Bool -> IO Bool
check name ok = do
  putStrLn ("  " ++ (if ok then "OK  " else "FAIL") ++ "  " ++ name)
  pure ok

main :: IO ()
main = do
  putStrLn "== Equational proofs and deterministic checks for Part IV =="
  putStrLn ""
  putStrLn "-- Section 1 (Theorem IV-A / thm:groth): universal property of group completion --"
  r1 <- sequence
    [ check "gamma is a monoid homomorphism (definitional)"                 check_gammaHom
    , check "GElt a b = gamma a - gamma b (definitional)"                   check_differenceDecomp
    , check "the relation t+a=t forces weight(a)=0 on any hom out of M"     check_respectsToyRelation
    , check "well-definedness: two representatives, same induced value"    wellDefinednessInstance
    , check "mkHom rejects a weighting that violates the relation"         rejectsBadWeighting
    , check "mkHom accepts a weighting that respects the relation"         acceptsGoodWeighting
    , check "existence/factorization: induced f . gamma = f"               check_factorization
    ]
  putStrLn ""
  putStrLn "-- Section 2 (Example 4.5 / ex:noncanc): K(toy monoid) = Z, generated by [t], [a]=0 --"
  r2 <- sequence
    [ check "toZ's weighting is mkHom-certified"                toZWeightingIsCertified
    , check "t^q is the q-fold sum of t (definitional)"         (all tPowerIsRepeatedSum [0 .. 8])
    , check "gamma(t^q) = q copies of gamma(t) (definitional)"  (all gammaOfTPowerIsQCopies [0 .. 8])
    , check "every multiple of a collapses to 0 in K(M)"        (all aMultiplesCollapse [0 .. 8])
    , check "toZ . fromZ = id on Z"                             (all toZFromZRoundTrip [-8 .. 8])
    , check "fromZ is injective (via the induced hom to Z)"     (and [ fromZInjective i j | i <- [-4 .. 4], j <- [-4 .. 4] ])
    , check "fromZ . toZ = id (up to eqG) on the a,t-carrier"   (all roundTripOntoCarrier atCarrier)
    ]
  putStrLn ""
  putStrLn "-- Section 3 (Proposition 5.8 / prop:bott): Bott periodicity and Table 1 landmarks --"
  r3 <- sequence
    [ check "mod-periodicity mechanism, transported through entryReal/entryComplex" check_modPeriodic
    , check "antidiagonal invariance is plain arithmetic, transported likewise"      check_antidiagonal
    , check "Table 1 landmarks via explicit (s-d) mod p arithmetic"                  check_landmarks
    , check "the same landmarks via the class-indexed 'invariant' entry point"       check_landmarksByClass
    ]
  putStrLn ""
  let results = r1 ++ r2 ++ r3
      passed  = length (filter id results)
      total   = length results
  putStrLn (show passed ++ "/" ++ show total ++ " proof checks passed")
  if and results
    then putStrLn "ALL EQUATIONAL PROOFS CHECKED" >> exitSuccess
    else putStrLn "SOME PROOF CHECKS FAILED" >> exitFailure
