// KaTeX macro tables for the six-part "topological phases of matter" series.
//
// Each paper's LaTeX preamble defines a canonical macro block shared verbatim
// across all six papers, plus a handful of paper-local macros. A few
// paper-local names collide (e.g. \id, \Groth, \real mean different things in
// different papers), so macros are resolved per paper slug rather than merged
// into one global table.

export type MacroMap = Record<string, string>;

// The canonical block present, verbatim, in every paper's preamble.
export const CANONICAL_MACROS: MacroMap = {
  '\\cond': '\\underline{#1}',
  '\\cg': '\\underline{#1}',
  '\\Cont': '\\operatorname{Cont}',
  '\\Shape': '\\operatorname{Shape}',
  '\\Int': '\\mathcal{I}',
  '\\Ffun': 'F',
  '\\BF': '\\mathcal{B}_{F}',
  '\\Ham': '\\mathfrak{Ham}',
  '\\Gap': '\\mathfrak{Gap}',
  '\\Phase': '\\mathfrak{Phase}',
  '\\Phases': '\\operatorname{Phases}',
  '\\Weq': '\\mathcal{W}',
  '\\st': '\\mathrm{st}',
  '\\hfix': 'h#1',
  '\\quotstack': '[#1/#2]',
  '\\gapof': '\\operatorname{gap}(#1)',
  '\\gapbound': '\\Delta',
  '\\IPcond': '\\mathbf{IP}^{\\mathrm{cond}}',
  '\\Sig': '\\Sigma',
  '\\rc': '\\partial\\nu',
  '\\Kop': 'K_{\\mathrm{op}}',
  '\\Kalg': 'K_{\\mathrm{alg}}',
  '\\Solid': '\\operatorname{Solid}',
  '\\dis': '\\Omega',
};

// Generic safety-net macros: standard notations that are not part of this
// series' canonical block but are cheap to define in case any paper leans on
// a physics-package shorthand KaTeX doesn't ship natively.
const SAFETY_MACROS: MacroMap = {
  '\\slashed': '\\not{#1}',
  '\\bra': '\\langle #1 |',
  '\\ket': '|#1\\rangle',
  '\\braket': '\\langle #1 \\vert #2 \\rangle',
  '\\Hom': '\\operatorname{Hom}',
  '\\Lan': '\\operatorname{Lan}',
  '\\Ran': '\\operatorname{Ran}',
};

// Paper-local macros, transcribed from each paper's own \newcommand block in
// papers/latex/<slug>.tex (everything after "end canonical macros").
export const PAPER_MACROS: Record<string, MacroMap> = {
  'bordism-realizability': {
    '\\real': '\\rho',
    '\\SRE': '\\mathrm{SRE}',
    '\\CP': '\\mathrm{CP}',
    '\\Maj': '\\mathcal{M}',
    '\\winding': 'w',
    '\\Ztwo': '\\mathbb{Z}_2',
    '\\Zint': '\\mathbb{Z}',
    '\\Circ': '\\mathbb{T}',
    '\\im': '\\operatorname{im}',
    '\\Pf': '\\operatorname{Pf}',
    '\\sgn': '\\operatorname{sgn}',
  },
  'lattice-eft-equivalence': {
    '\\Pic': '\\operatorname{Pic}',
    '\\Groth': 'K',
    '\\Sph': '\\mathbb{S}',
    '\\IZ': 'I_{\\mathbb{Z}}',
    '\\IFH': '\\mathbf{I}_{\\mathrm{FH}}',
    '\\Zp': '\\mathbb{Z}',
    '\\Rp': '\\mathbb{R}',
    '\\Tt': '\\mathbb{T}',
    '\\MTH': '\\mathit{MTH}',
    '\\triv': '\\mathbf{1}',
    '\\inv': '\\Phase_{#1}^{\\times}',
    '\\coker': '\\operatorname{coker}',
    '\\im': '\\operatorname{im}',
    '\\Map': '\\operatorname{Map}',
    '\\colim': '\\operatorname{colim}',
    '\\KO': '\\operatorname{KO}',
  },
  'lieb-robinson-locality': {
    '\\qA': '\\mathcal{A}',
    '\\Aut': '\\operatorname{Aut}',
    '\\Der': '\\operatorname{Der}',
    '\\id': '\\mathrm{id}',
    '\\Ball': '\\mathcal{B}_{F}(#1)',
    '\\norm': '\\lVert #1\\rVert',
    '\\Fnorm': '\\lVert #1\\rVert_{F}',
    '\\Fanorm': '\\lVert #1\\rVert_{F_a}',
    '\\loc': '\\mathrm{loc}',
    '\\supp': '\\operatorname{supp}',
    '\\dist': '\\operatorname{dist}',
    '\\R': '\\mathbb{R}',
    '\\C': '\\mathbb{C}',
    '\\Z': '\\mathbb{Z}',
    '\\N': '\\mathbb{N}',
    '\\Set': '\\mathbf{Cond}',
    '\\lCond': '\\mathbf{Cond}^{\\mathrm{light}}',
    '\\eqdef': '\\coloneqq',
  },
  'positivity-cstar-norms': {
    '\\qla': '\\mathcal{A}',
    '\\loc': '\\mathrm{loc}',
    '\\St': '\\mathcal{S}',
    '\\Pu': '\\mathcal{P}',
    '\\Hil': '\\mathcal{H}',
    '\\Rep': '\\pi',
    '\\cyc': '\\Omega_{\\phi}',
    '\\Aut': '\\operatorname{Aut}',
    '\\Prob': '\\operatorname{Prob}',
    '\\dalg': '\\mathfrak{A}',
    '\\CAlg': '\\mathsf{C^{*}Alg}',
    '\\CStar': '\\mathsf{C^{*}St}',
    '\\Cond': '\\mathsf{Cond}',
    '\\RR': '\\mathbb{R}',
    '\\CC': '\\mathbb{C}',
    '\\ZZ': '\\mathbb{Z}',
    '\\NN': '\\mathbb{N}',
    '\\TT': '\\mathbb{T}',
    '\\Mn': 'M_{n}(\\mathbb{C})',
    '\\wkstar': '\\mathrm{w\\text{-}\\ast}',
    '\\norm': '\\lVert #1 \\rVert',
    '\\abs': '\\lvert #1 \\rvert',
    '\\ip': '\\langle #1 , #2 \\rangle',
    '\\rank': '\\operatorname{rank}',
    '\\Tr': '\\operatorname{Tr}',
    '\\id': '\\mathbf{1}',
    '\\ev': '\\operatorname{ev}',
  },
  'spectral-gap-stability': {
    '\\R': '\\mathbb{R}',
    '\\C': '\\mathbb{C}',
    '\\Z': '\\mathbb{Z}',
    '\\N': '\\mathbb{N}',
    '\\Hilb': '\\mathcal{H}',
    '\\Alg': '\\mathcal{A}',
    '\\gsp': '\\mathcal{G}',
    '\\norm': '\\lVert #1 \\rVert',
    '\\abs': '\\lvert #1 \\rvert',
    '\\ip': '\\langle #1 \\rangle',
    '\\set': '\\{\\,#1\\,\\}',
    '\\gapfin': '\\operatorname{gap}_{#1}',
    '\\Tr': '\\operatorname{Tr}',
    '\\supp': '\\operatorname{supp}',
    '\\dist': '\\operatorname{dist}',
    '\\einf': '\\operatorname*{inf}',
  },
  synthesis: {
    '\\RR': '\\mathbb{R}',
    '\\CC': '\\mathbb{C}',
    '\\ZZ': '\\mathbb{Z}',
    '\\NN': '\\mathbb{N}',
    '\\Uone': 'U(1)',
    '\\Hilb': '\\mathcal{H}',
    '\\qA': '\\mathcal{A}',
    '\\St': '\\mathcal{S}',
    '\\Aut': '\\operatorname{Aut}',
    '\\SRE': '\\mathrm{SRE}',
    '\\Groth': '\\operatorname{Groth}',
    '\\IFH': 'I_{\\mathrm{FH}}',
    '\\real': '\\operatorname{real}',
    '\\CPr': '\\mathrm{cp}',
    '\\Obs': '\\operatorname{Obs}',
    '\\norm': '\\lVert #1 \\rVert',
    '\\abs': '\\lvert #1 \\rvert',
    '\\set': '\\{\\,#1\\,\\}',
    '\\dist': '\\operatorname{dist}',
    '\\im': '\\operatorname{im}',
    '\\id': '\\mathrm{id}',
    '\\einf': '\\operatorname*{inf}',
  },
};

export function getMacrosForSlug(slug: string): MacroMap {
  return {
    ...CANONICAL_MACROS,
    ...SAFETY_MACROS,
    ...(PAPER_MACROS[slug] ?? {}),
  };
}
